### PR TITLE
Issue that I opened. "--break-system-packages with pip"

### PR DESCRIPTION
**Pull request by midnit3Z0mbi3**
Hello, I tried installing X-osint on my Debian 12 VM on VirtualBox, but was unable to install. I fixed the issue by creating a python virtual environment and appending "--break-system-packages" on each "pip install" entry on the setup.sh file. I don't know if that is good or not. I just know that X-osint works perfectly with those edits.

### CODE REVIEW

**Comment by midnit3Z0mbi3** [comment]
Updated the README.md

**Comment by midnit3Z0mbi3** [comment]
Updated the README.md

**Comment by TermuxHackz** [comment]
@midnit3Z0mbi3 would definitely check it out on my side to see if it works well, much appreciated

**Comment by midnit3Z0mbi3** [comment]
It works. I just tested it on a Debian 12 VM on VirtualBox.

**Comment by TermuxHackz** [comment]
@midnit3Z0mbi3 Glad it does, would merge pull request in a little while, would go a test on all systems, Cheers mate !

**Comment by midnit3Z0mbi3** [comment]
@TermuxHackz Great. 👍 Thanks. Cheers! 😊 😌

**Pull request closed without merging**
