### PR TITLE
Redo of Pull Request. Update setup.sh

### PR DESCRIPTION
**Pull request by midnit3Z0mbi3**
I had to redo the pull request. I only made edits to the setup.sh, not the README.md.

### CODE REVIEW

**Comment by midnit3Z0mbi3** [comment]
Nice. I see you put the changes I asked. Thanks... BTW, X-osint looks amazing!

**Comment by midnit3Z0mbi3** [comment]
Is payment required now? I saw a new message after running X-osint for the first time. It said something to the extent, " if you don't contribute to X-osint the tool wont work well for you." 

What does that mean? I wont have access to certain features?

**Comment by midnit3Z0mbi3** [comment]
NVM

**Comment by TermuxHackz** [comment]
@midnit3Z0mbi3 nope, all features would still work, payment is optional and it’s not compulsory, you would always click “no” and it would still work as normal

**Pull request closed without merging**
